version: "3"



services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '1111:3306'

  pypypy:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8888:8888'
    command: bash -c "
        python insurance/manage.py makemigrations &&
        python insurance/manage.py migrate &&
        python insurance/manage.py loaddata insurance/init_db.json &&
        python insurance/manage.py runserver 0.0.0.0:8888
        "