version: "3"



services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '1111:3306'

  # pypypy:
  #   depends_on:
  #     - postgres
  #   build:
  #     context: ./
  #     dockerfile: docker-11/Dockerfile
  #   ports:
  #     - '8888:8888'
  #   command: bash -c "
  #       python prac11/manage.py makemigrations &&
  #       python prac11/manage.py migrate &&
  #       python prac11/manage.py runserver 0.0.0.0:8888
  #       "