# Generated by Django 5.0 on 2023-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
